# Generated by Django 3.2.16 on 2022-11-28 05:02

import boardapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('sns_image', models.ImageField(blank=True, null=True, upload_to=boardapp.models.image_directory_path)),
                ('good', models.IntegerField(default=0)),
                ('good_user', models.TextField(default='')),
                ('read', models.IntegerField(default=0)),
                ('read_text', models.TextField()),
            ],
        ),
    ]
