# Generated by Django 3.2.8 on 2022-10-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0004_auto_20221011_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='author',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
