# Generated by Django 3.2.8 on 2022-10-11 01:15

import boardapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0006_alter_boardmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='sns_image',
            field=models.ImageField(blank=True, null=True, upload_to=boardapp.models.image_directory_path),
        ),
    ]
