# Generated by Django 3.2.8 on 2022-10-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0007_alter_boardmodel_sns_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
