# Generated by Django 3.2.8 on 2022-10-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0008_alter_boardmodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
