# Generated by Django 3.2.16 on 2022-11-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0010_likemodel_readmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likemodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='readmodel',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='post',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='likemodel',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
