# Generated by Django 3.2.16 on 2022-11-28 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0011_auto_20221128_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likemodel',
            old_name='post',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='likemodel',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='readmodel',
            old_name='post',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='readmodel',
            old_name='user',
            new_name='user_id',
        ),
    ]
