# Generated by Django 3.2.16 on 2022-11-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0012_auto_20221128_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likemodel',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
